# Generated by Django 5.1.1 on 2024-10-08 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='perfil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
            preserve_default=False,
        ),
    ]
