# Generated by Django 5.1.1 on 2024-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_potas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Potas',
        ),
    ]
