# Generated by Django 5.1.3 on 2024-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_delete_potas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
