# Generated by Django 5.1.1 on 2024-09-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        ('project', '0005_project_contractor'),
        ('user', '0009_rename_confirmation_token_user_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payement_type', models.IntegerField(choices=[(1, 'Pix'), (2, 'Debit'), (3, 'Credit')], default=1, verbose_name='Pix')),
                ('delivery', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.area')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('my_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.mycompetency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.subarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
