# Generated by Django 5.1.1 on 2024-09-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_acceptproposal_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.language'),
        ),
    ]
