# Generated by Django 5.1.1 on 2024-09-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('proposal', '0004_alter_proposal_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='perfil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
            preserve_default=False,
        ),
    ]
