# Generated by Django 5.1.1 on 2024-09-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_remove_proposal_user_proposal_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='in_execution',
            field=models.BooleanField(default=False),
        ),
    ]
