# Generated by Django 5.1.1 on 2024-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_proposal_in_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptproposal',
            name='date',
            field=models.DateField(),
        ),
    ]
