# Generated by Django 5.1.1 on 2024-09-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_alter_acceptproposal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptproposal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
