# Generated by Django 5.1.3 on 2024-11-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_about_me'),
        ('proposal', '0009_remove_proposal_in_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='my_competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.mycompetency'),
        ),
    ]
