# Generated by Django 5.1.1 on 2024-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_price_contractservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractservice',
            name='service',
        ),
        migrations.AddField(
            model_name='contractservice',
            name='type_of_service',
            field=models.IntegerField(choices=[(1, 'FREE'), (2, 'Month'), (3, 'YEAR')], default=1, verbose_name='Type of user'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
