# Generated by Django 5.1.3 on 2024-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_contractservice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractservice',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
