# Generated by Django 5.1.3 on 2024-11-22 19:40

import uploader.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_base64',
            field=models.TextField(blank=True, help_text='Store the base64 encoded image.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=uploader.models.image.image_file_path),
        ),
    ]
