# Generated by Django 5.1.3 on 2024-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID from Cloudinary, used to retrieve the image file.', max_length=255, null=True, unique=True),
        ),
    ]
