# Generated by Django 5.1.3 on 2024-11-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_remove_address_zip_code_city_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='complemement',
            new_name='complement',
        ),
    ]
