# Generated by Django 5.1.3 on 2024-11-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_rename_complemement_address_complement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='neighborhood_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
    ]
