# Generated by Django 5.1.3 on 2024-11-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_remove_address_neighborhood_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='complement',
        ),
    ]
