# Generated by Django 5.1.3 on 2024-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
