# Generated by Django 5.1.3 on 2024-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_transaction_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
