# Generated by Django 5.1.3 on 2024-11-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_alter_transaction_created_at'),
        ('proposal', '0010_alter_proposal_my_competency'),
        ('service', '0004_contractservice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='accept_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.acceptproposal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.contractservice'),
        ),
    ]
