# Generated by Django 5.1.1 on 2024-09-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        ('proposal', '0009_remove_proposal_in_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_body', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_accept', models.BooleanField(default=False)),
                ('accept_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.acceptproposal')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
    ]
