# Generated by Django 5.1.1 on 2024-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='report',
            field=models.FileField(upload_to='report'),
        ),
    ]
