# Generated by Django 5.1.1 on 2024-09-21 20:30

import uploader.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_pdf_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='report',
            field=models.FileField(upload_to=uploader.models.document.document_file_path),
        ),
    ]
