# Generated by Django 5.1.1 on 2024-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_pdf_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='hours',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
