# Generated by Django 5.1.1 on 2024-09-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_report_date_report_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='report',
            name='perfil',
        ),
    ]
