# Generated by Django 5.1.3 on 2024-11-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_report_hours_remove_report_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
