# Generated by Django 5.1.3 on 2024-11-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_text_body_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text_body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
