# Generated by Django 5.1.1 on 2024-09-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('project', '0002_project_crontractor'),
        ('user', '0009_rename_confirmation_token_user_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hability', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MyHability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
                ('user_hability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfil.hability')),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Finished')], default=1, verbose_name='status')),
                ('term', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=45)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=9999999999999999)),
                ('is_public', models.BooleanField(default=True)),
                ('about_me', models.CharField(max_length=255)),
                ('category_Feelance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfil.categoriafreelancer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
