# Generated by Django 5.1.3 on 2024-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='number_projects_in_execution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
