# Generated by Django 5.1.1 on 2024-09-11 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_myhability_user_myhability_perfil_and_more'),
        ('project', '0002_project_crontractor'),
        ('uploader', '0001_initial'),
        ('user', '0009_rename_confirmation_token_user_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='CategoriaFreelancer',
            new_name='SubArea',
        ),
        migrations.RemoveField(
            model_name='myproject',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='myproject',
            name='project',
        ),
        migrations.RenameField(
            model_name='hability',
            old_name='hability',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='category_Feelance',
        ),
        migrations.AddField(
            model_name='perfil',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Pix'), (2, 'Debito'), (3, 'Credito')], default=1, verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='uploader.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='sub_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_area', to='perfil.subarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='perfil.area'),
        ),
        migrations.CreateModel(
            name='MyCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '1'), (2, '1 - 3'), (3, '3 - 5'), (4, '5 - more')], default=2, verbose_name='Time of experience')),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.document')),
                ('my_hability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.hability')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_execution', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nacionality', to='perfil.nacionality'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('become_pro', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='MyHability',
        ),
        migrations.DeleteModel(
            name='MyProject',
        ),
    ]
