# Generated by Django 5.1.3 on 2024-11-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_number_projects_in_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_pro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
