# Generated by Django 5.1.1 on 2024-09-11 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_subarea_area'),
        ('project', '0003_rename_crontractor_project_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='perfil.perfil'),
        ),
    ]
