# Generated by Django 5.1.1 on 2024-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_myprojects_project_alter_myprojects_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
