# Generated by Django 5.1.3 on 2024-12-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_perfil_access_token_mercado_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAvaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_number', models.IntegerField()),
                ('perfil_avaliator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to='perfil.perfil')),
                ('perfil_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to='perfil.perfil')),
            ],
        ),
    ]
