# Generated by Django 5.1.1 on 2024-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_pro_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompetency',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
