# Generated by Django 5.1.3 on 2024-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_perfilavaliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avaliation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
