# Generated by Django 5.1.1 on 2024-09-14 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_mycompetency_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.myprojects')),
            ],
        ),
    ]
