# Generated by Django 5.1.3 on 2024-12-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_perfil_avaliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='every_avaliations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
