# Generated by Django 5.1.3 on 2024-12-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_perfil_every_avaliations'),
        ('uploader', '0002_alter_image_file_alter_image_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.image'),
        ),
    ]
