import requests
cities_data = [
    {"city": "São Paulo", "state": "São Paulo", "country": "Brazil", "code": "01000-000"},
    {"city": "Rio de Janeiro", "state": "Rio de Janeiro", "country": "Brazil", "code": "20000-000"},
    {"city": "Belo Horizonte", "state": "Minas Gerais", "country": "Brazil", "code": "30100-000"},
    {"city": "Porto Alegre", "state": "Rio Grande do Sul", "country": "Brazil", "code": "90000-000"},
    {"city": "Salvador", "state": "Bahia", "country": "Brazil", "code": "40000-000"},
    {"city": "Fortaleza", "state": "Ceará", "country": "Brazil", "code": "60000-000"},
    {"city": "Curitiba", "state": "Paraná", "country": "Brazil", "code": "80000-000"},
    {"city": "Manaus", "state": "Amazonas", "country": "Brazil", "code": "69000-000"},
    {"city": "Recife", "state": "Pernambuco", "country": "Brazil", "code": "50000-000"},
    {"city": "Brasília", "state": "Distrito Federal", "country": "Brazil", "code": "70000-000"},
    {"city": "Goiânia", "state": "Goiás", "country": "Brazil", "code": "74000-000"},
    {"city": "Campinas", "state": "São Paulo", "country": "Brazil", "code": "13000-000"},
    {"city": "São Luís", "state": "Maranhão", "country": "Brazil", "code": "65000-000"},
    {"city": "Natal", "state": "Rio Grande do Norte", "country": "Brazil", "code": "59000-000"},
    {"city": "Maceió", "state": "Alagoas", "country": "Brazil", "code": "57000-000"},
    {"city": "Teresina", "state": "Piauí", "country": "Brazil", "code": "64000-000"},
    {"city": "Vitória", "state": "Espírito Santo", "country": "Brazil", "code": "29000-000"},
    {"city": "Belém", "state": "Pará", "country": "Brazil", "code": "66000-000"},
    {"city": "Santos", "state": "São Paulo", "country": "Brazil", "code": "11000-000"},
    {"city": "São Bernardo do Campo", "state": "São Paulo", "country": "Brazil", "code": "09700-000"},
    {"city": "Diadema", "state": "São Paulo", "country": "Brazil", "code": "09900-000"},
    {"city": "João Pessoa", "state": "Paraíba", "country": "Brazil", "code": "58000-000"},
    {"city": "São Gonçalo", "state": "Rio de Janeiro", "country": "Brazil", "code": "24400-000"},
    {"city": "Osasco", "state": "São Paulo", "country": "Brazil", "code": "06000-000"},
    {"city": "Jundiaí", "state": "São Paulo", "country": "Brazil", "code": "13200-000"},
    {"city": "Mogi das Cruzes", "state": "São Paulo", "country": "Brazil", "code": "08700-000"},
    {"city": "Sorocaba", "state": "São Paulo", "country": "Brazil", "code": "18000-000"},
    {"city": "Ribeirão Preto", "state": "São Paulo", "country": "Brazil", "code": "14000-000"},
    {"city": "Cuiabá", "state": "Mato Grosso", "country": "Brazil", "code": "78000-000"},
    {"city": "São José dos Campos", "state": "São Paulo", "country": "Brazil", "code": "12200-000"},
    {"city": "Pelotas", "state": "Rio Grande do Sul", "country": "Brazil", "code": "96000-000"},
    {"city": "Aracaju", "state": "Sergipe", "country": "Brazil", "code": "49000-000"},
    {"city": "Rio Preto", "state": "São Paulo", "country": "Brazil", "code": "15000-000"},
    {"city": "Ponta Grossa", "state": "Paraná", "country": "Brazil", "code": "84000-000"},
    {"city": "Maringá", "state": "Paraná", "country": "Brazil", "code": "87000-000"},
    {"city": "Cascavel", "state": "Paraná", "country": "Brazil", "code": "85800-000"},
    {"city": "Londrina", "state": "Paraná", "country": "Brazil", "code": "86000-000"},
    {"city": "Uberlândia", "state": "Minas Gerais", "country": "Brazil", "code": "38400-000"},
    {"city": "Bauru", "state": "São Paulo", "country": "Brazil", "code": "17000-000"},
    {"city": "Aparecida de Goiânia", "state": "Goiás", "country": "Brazil", "code": "74900-000"},
    {"city": "São José do Rio Preto", "state": "São Paulo", "country": "Brazil", "code": "15000-000"},
    {"city": "Franca", "state": "São Paulo", "country": "Brazil", "code": "14400-000"},
    {"city": "Caxias do Sul", "state": "Rio Grande do Sul", "country": "Brazil", "code": "95000-000"},
    {"city": "São José", "state": "Santa Catarina", "country": "Brazil", "code": "88100-000"},
    {"city": "Lajeado", "state": "Rio Grande do Sul", "country": "Brazil", "code": "95900-000"},
    {"city": "Chapecó", "state": "Santa Catarina", "country": "Brazil", "code": "89800-000"},
    {"city": "Barueri", "state": "São Paulo", "country": "Brazil", "code": "06400-000"},
    {"city": "Itu", "state": "São Paulo", "country": "Brazil", "code": "13300-000"},
    {"city": "Limeira", "state": "São Paulo", "country": "Brazil", "code": "13400-000"},
    {"city": "Taubaté", "state": "São Paulo", "country": "Brazil", "code": "12000-000"},
    {"city": "Caruaru", "state": "Pernambuco", "country": "Brazil", "code": "55000-000"},
    {"city": "Iguaçu", "state": "Paraná", "country": "Brazil", "code": "85500-000"},
    {"city": "Porto Velho", "state": "Rondônia", "country": "Brazil", "code": "76800-000"}
]

for c in cities_data:
    response = requests.post("http://127.0.0.1:8000/api/pay/city", json=c)
    print(response.status_code)