# Generated by Django 5.1.1 on 2024-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=45)),
                ('sub_area', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('subTitlte', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=45)),
                ('demands', models.CharField(max_length=45)),
                ('nivel_development', models.CharField(max_length=45)),
                ('need_api_integration', models.CharField(max_length=45)),
                ('need_frameworks', models.CharField(max_length=45)),
                ('experiente_required', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'INTERMEDIARIO'), (3, 'EXPERIENTE'), (4, 'ESPECIALISTA')], default=2, verbose_name='Experience')),
                ('budget', models.IntegerField(choices=[(1, '100 - 1000'), (2, '1000 - 5000'), (3, '5000 - 10000'), (4, '10001 - 10000000000000000000000')], default=2, verbose_name='Budget')),
                ('size', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Big'), (4, 'Giant')], default=2, verbose_name='Size')),
            ],
        ),
    ]
