# Generated by Django 5.1.1 on 2024-09-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0009_rename_confirmation_token_user_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crontractor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='user.user'),
            preserve_default=False,
        ),
    ]
