# Generated by Django 5.1.1 on 2024-09-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_crontractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='crontractor',
            new_name='contractor',
        ),
    ]
