# Generated by Django 5.1.1 on 2024-09-15 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_crontractor_project_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='area',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demands',
        ),
        migrations.RemoveField(
            model_name='project',
            name='experiente_required',
        ),
        migrations.RemoveField(
            model_name='project',
            name='need_api_integration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='need_frameworks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nivel_development',
        ),
        migrations.RemoveField(
            model_name='project',
            name='size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subTitlte',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_area',
        ),
        migrations.AddField(
            model_name='project',
            name='budget_range',
            field=models.IntegerField(choices=[(1, 'R$100 - 1.000'), (2, 'R$1.000 - 5.000'), (3, 'R$5.000 - 10.000'), (4, 'Mais de R$10.000')], default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='development_level',
            field=models.IntegerField(choices=[(1, "I don't have nothing"), (2, 'I have a idea'), (3, 'I have a design')], default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Experiente'), (4, 'Especialista')], default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='function',
            field=models.IntegerField(choices=[(1, 'Web_design'), (2, 'Mobile_design'), (3, 'Manager'), (4, 'Other')], default=4, verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_size',
            field=models.IntegerField(choices=[(1, 'Pequeno'), (2, 'Intermediário'), (3, 'Grande'), (4, 'Gigante')], default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='special_resouce',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'Perhaps'), (3, 'NO')], default=3, verbose_name='Special Resource'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='context',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.integrationtype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
            ],
        ),
    ]
