# Generated by Django 5.1.1 on 2024-09-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_finished_project_pending_finishedproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finished',
        ),
    ]
