# Generated by Django 5.1.3 on 2024-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='response_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
