# Generated by Django 5.1.1 on 2024-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_forgetpassword'),
        ('user', '0007_emailverification'),
    ]

    operations = [
    ]
