# Generated by Django 5.1.1 on 2024-09-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_0003_forgetpassword_0007_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_token',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
