# Generated by Django 5.1.1 on 2024-10-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_emailverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Contractors'), (3, 'Freelancers')], default=3, null=True, verbose_name='Type of user'),
        ),
    ]
